/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.115
 * Generated at: 2026-03-07 06:05:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Iterator;
import java.util.List;
import in.co.rays.bean.UserBean;

public final class UserListView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/Header.jsp", Long.valueOf(1772862810000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("in.co.rays.bean.UserBean");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.util.Iterator");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"ISO-8859-1\">\n");
      out.write("<title>Insert title here</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("	");

	List<UserBean> list = (List<UserBean>) request.getAttribute("list");
	String smsg = (String) request.getAttribute("successMsg");
	String emsg = (String) request.getAttribute("errorMsg");
	int index = 1;
	
      out.write('\n');
      out.write('\n');
      out.write('	');
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"ISO-8859-1\">\n");
      out.write("<title>Insert title here</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("	");

	UserBean userBean = (UserBean) session.getAttribute("user");
	
      out.write('\n');
      out.write('\n');
      out.write('	');

	if (userBean != null) {
	
      out.write("\n");
      out.write("	<h3>");
      out.print("Hii, " + userBean.getFirstName());
      out.write("</h3>\n");
      out.write("	<a href=\"UserCtl.do\">Add User</a> |\n");
      out.write("	<a href=\"UserListCtl.do\">User list</a> |\n");
      out.write("	<a href=\"LoginCtl?operation=logout\">Logout</a> \n");
      out.write("	");

	} else {
	
      out.write("\n");
      out.write("\n");
      out.write("	<h3>Hi, Guest</h3>\n");
      out.write("	<a href=\"LoginCtl\">Login</a> |\n");
      out.write("	<a href=\"UserRegistrationCtl\">SignUp</a> |\n");
      out.write("	<a href=\"WelcomeCtl\">Welcome</a>\n");
      out.write("\n");
      out.write("	");

	}
	
      out.write("\n");
      out.write("	<hr>\n");
      out.write("</body>\n");
      out.write("</html>");
      out.write("\n");
      out.write("	<div align=\"center\">\n");
      out.write("		<h1>User List</h1>\n");
      out.write("		<h3 style=\"color: green;\">");
      out.print(smsg != null ? smsg : "");
      out.write("</h3>\n");
      out.write("		<h3 style=\"color: red;\">");
      out.print(emsg != null ? emsg : "");
      out.write("</h3>\n");
      out.write("		<form action=\"UserListCtl.do\" method=\"post\">\n");
      out.write("\n");
      out.write("			<table>\n");
      out.write("				<tr>\n");
      out.write("					<th>First Name</th>\n");
      out.write("					<td><input type=\"text\" name=\"firstName\" value=\"\"\n");
      out.write("						placeholder=\"search by firstName\"></td>\n");
      out.write("					<th>Last Name</th>\n");
      out.write("					<td><input type=\"text\" name=\"lastName\" value=\"\"\n");
      out.write("						placeholder=\"search by lastName\"></td>\n");
      out.write("					<td><input type=\"submit\" name=\"operation\" value=\"search\"></td>\n");
      out.write("				</tr>\n");
      out.write("			</table>\n");
      out.write("\n");
      out.write("			<table border=\"1px\" width=\"100%\">\n");
      out.write("				<tr style=\"background-color: skyblue\">\n");
      out.write("					<th>Select</th>\n");
      out.write("					<th>Id</th>\n");
      out.write("					<th>First Name</th>\n");
      out.write("					<th>Last Name</th>\n");
      out.write("					<th>Login</th>\n");
      out.write("					<th>Password</th>\n");
      out.write("					<th>Dob</th>\n");
      out.write("					<th>Edit</th>\n");
      out.write("				</tr>\n");
      out.write("\n");
      out.write("\n");
      out.write("				");

				Iterator<UserBean> it = list.iterator();

				while (it.hasNext()) {
					UserBean bean = it.next();
				
      out.write("\n");
      out.write("				<tr align=\"center\">\n");
      out.write("					<td><input type=\"checkbox\" name=\"ids\"\n");
      out.write("						value=\"");
      out.print(bean.getId());
      out.write("\"></td>\n");
      out.write("					<td>");
      out.print(index++);
      out.write("</td>\n");
      out.write("					<td>");
      out.print(bean.getFirstName());
      out.write("</td>\n");
      out.write("					<td>");
      out.print(bean.getLastName());
      out.write("</td>\n");
      out.write("					<td>");
      out.print(bean.getLogin());
      out.write("</td>\n");
      out.write("					<td>");
      out.print(bean.getPassword());
      out.write("</td>\n");
      out.write("					<td>");
      out.print(bean.getDob());
      out.write("</td>\n");
      out.write("					<td><a href=\"UserCtl.do?id=");
      out.print(bean.getId());
      out.write("\">Edit</a></td>\n");
      out.write("				</tr>\n");
      out.write("\n");
      out.write("				");

				}
				
      out.write("\n");
      out.write("			</table>\n");
      out.write("			<br>\n");
      out.write("			<table width=\"100%\">\n");
      out.write("				<tr>\n");
      out.write("					<td align=\"center\"><input type=\"submit\" name=\"operation\"\n");
      out.write("						value=\"delete\"></td>\n");
      out.write("				</tr>\n");
      out.write("			</table>\n");
      out.write("		</form>\n");
      out.write("\n");
      out.write("	</div>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
